services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: server
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - server_node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run devStart"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb


  client:
    container_name: client
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      # - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    depends_on:
    - server  #

  studio:
    container_name: prisma-studio
    image: node:18  
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npx prisma studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db
volumes:
  postgres_data:
  server_node_modules:
