services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run devStart"

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      # - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
